apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : "${PRECONFIG_APPLICATION_NAME}"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name     : in-cluster
    namespace: "${NAMESPACE}"
  source:
    path   : "HelmCharts/initial-configuration-keycloak"
    repoURL: "git@github.com:BohdanBohatov/argocd-keycloak.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - "./CompaniesValues/${PRECONFIG_VALUES_FILE}"
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true