apiVersion: v1
kind: Secret
metadata:
  name: "${POSTGRES_SECRET_NAME}"
  namespace: "${NAMESPACE}"
  labels:
    app.kubernetes.io/instance: ${APPLICATION_NAME}
    app.kubernetes.io/name: postgresql
type: Opaque
data:
  password: "${POSTGRES_USER_PASSWORD}" 
  postgres-password: "${POSTGRES_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "${KEYCLOAK_SECRET_NAME}"
  namespace: "${NAMESPACE}"
  labels:
    app.kubernetes.io/instance: ${APPLICATION_NAME}
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  admin-password: "${ADMIN_USER_PASSWORD}"