apiVersion: v1
kind: Pod
metadata:
  name: efs-app-2
  namespace: efs-2
  annotations:
    meta.helm.sh/release-name: efs-release
    meta.helm.sh/release-namespace: efs-2
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: efs-storage
      mountPath: /data
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs-claim-second