apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.generalPersistentVolume.name }}
spec:
  storageClassName: {{ .Values.generalStorageClass.storageName }}
  capacity:
    storage: {{ .Values.generalPersistentVolume.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.generalPersistentVolume.hostPath }}