---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecret.postgresSecretName }}
  namespace: {{  required "Error: Namespace must be provided" ( .Values.namespace ) }}
spec:
  encryptedData:
    password: {{ .Values.sealedSecret.customUserSealedPassword }}
    postgres-password: {{ .Values.sealedSecret.postgresSealedPassword }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: {{ .Values.sealedSecret.instanceLabel }}
        app.kubernetes.io/name: postgresql
      name: {{ .Values.sealedSecret.postgresSecretName }}
      namespace: {{  required "Error: Namespace must be provided" ( .Values.namespace ) }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecret.keycloakSecretName }}
  namespace: {{  required "Error: Namespace must be provided" ( .Values.namespace ) }}
spec:
  encryptedData:
    admin-password: {{ .Values.sealedSecret.adminSealedPassword }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: keycloak
        app.kubernetes.io/instance: {{ .Values.sealedSecret.instanceLabel }}
        app.kubernetes.io/name: keycloak
      name: {{ .Values.sealedSecret.keycloakSecretName }}
      namespace: {{  required "Error: Namespace must be provided" ( .Values.namespace ) }}
    type: Opaque
