---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.postgresSecretName }}
  namespace: {{  required "Error: Namespace must be provided" ( .Values.namespace ) }}
spec:
  encryptedData:
    password: {{ .Values.customUserSealedPassword }}
    postgres-password: {{ .Values.postgresSealedPassword }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: {{ .Values.instanceLabel }}
        app.kubernetes.io/name: postgresql
      name: {{ .Values.postgresSecretName }}
      namespace: {{  required "Error: Namespace must be provided" ( .Values.namespace ) }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.keycloakSecretName }}
  namespace: {{  required "Error: Namespace must be provided" ( .Values.namespace ) }}
spec:
  encryptedData:
    admin-password: {{ .Values.adminSealedPassword }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: keycloak
        app.kubernetes.io/instance: {{ .Values.instanceLabel }}
        app.kubernetes.io/name: keycloak
      name: {{ .Values.keycloakSecretName }}
      namespace: {{  required "Error: Namespace must be provided" ( .Values.namespace ) }}
    type: Opaque
