apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.tlsCertificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: {{ .Values.tlsCertificate.server }}
    email: {{ .Values.tlsCertificate.email }}
    privateKeySecretRef:
      name: {{ .Values.tlsCertificate.privateKeyName }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.tlsCertificate.ingressClass }}