apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.tlsCertificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: {{ .Values.tlsCertificate.server }}
    email: {{ .Values.tlsCertificate.email }}
    privateKeySecretRef: {{ .Values.tlsCertificate.secretName }}
      name: 
    solvers:
    - http01:
        ingress:
          class: {{.Values.tlsCertificate.ingressClass }}