apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : efs-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name     : in-cluster
    namespace: efs-2
  source:
    path   : "HelmCharts/efscharts/efs"
    repoURL: "git@github.com:BohdanBohatov/argocd-keycloak.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOption:
      - CreateNamespace=true
