apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : efs-storageclass-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name     : in-cluster
    namespace: default
  source:
    path   : "Configuration/storageclass"
    repoURL: "git@github.com:BohdanBohatov/argocd-keycloak.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
