## @param namespace place where the chart will be stored
#
namespace: "company-1-ns"

## @param generalStorageClass responsible for creating persistance volume which will be used in keycloak mounting
# this value in system in persistanceVolume
generalStorageClass:
  storageName: "keycloak-company-1-storage-class"
  provisioner: kubernetes.io/no-provisioner

## @param generalPersistentVolume used for storing keycloak data
##
generalPersistentVolume:
  ## @param generalPersistentVolume.name must be unic for the whole cluster
  ##
  name: "keycloak-general-pv-company-1"
  ## @param generalPersistentVolume.capacity - must be the same that in keycloak, could be increased 
  ##
  capacity: 8Gi
  hostPath: "/mnt/data/keycloak/company-1"

## @param efsStorage must be linked to existing storageClass
#
efsStorage:
  storageName: "efs-sc"
  provisioner: efs.csi.aws.com

## @param efsPersistentVolume - used for provisioning efs storage
##
efsPersistentVolume:
  ## @param efsPersistentVolume.name must be unic for the whole cluster
  ##
  name: "keycloak-efs-pv-company-1"
  capacity: 1Gi
  ## @param efsPersistentVolume.volumeHandle - EFS the same for each keycloak customer, 
  ## way unic for each customer to avoid sharing the same files, 
  ## ATTENTION folder must be created before provisioning
  ##
  volumeHandle: "fs-0db109d8bea20374f:/keycloak/user-3-themes"

## @param efsPersistentVolumeClaim 
##
efsPersistentVolumeClaim:
  name: "keycloak-pv-claim"
  requestStorage: 1Gi

tlsCertificate:
  name: "keycloak-staging"
  server: "https://acme-staging-v02.api.letsencrypt.org/directory" #"https://acme-v02.api.letsencrypt.org/directory"
  email: "bbohatovmif@gmail.com"
  ingressClass: nginx
  privateKeyName: prod-secret-key

sealedSecret:
  postgresSecretName: "keycloak-postgresql-company-1-secret"
  keycloakSecretName: "keycloak-app-company-1-secret"
  instanceLabel: "keycloak-company-1-application"
  adminSealedPassword: "AgAzVE0Nw28S0DTRisIT39XIAYAQePQANHJJoQ/26dgLGLrgMsDdRgYccc1GrfuN84elRZbQbM+ccskDn9AJ2ZJidQ0WA7O3g91O7UdqQSlHqwJebVg3Oaya9RTz1gO7y/IbOhIs0TrSFG/zJ1T+Fn/zMydP2VhJ5i/fqwuMoLQrBJ+7Z4IMxhdlbnwPcqt3M91UcmNgy/FKFzof2+rlrhVd6f+VDvIVeFSv2s2lVRlfD1YV3EcGDu+O02S9B/1UlpByUIbFmp3CSU199k5P1XD20bcByYNqQLVyHqzCiFu9YxfRD4hmIzwBxjw33lA/AjqsyKQxiO0RDCTxYe9d/WlJZAewKb27QFVHuooEKt/APcfr7AVNuJsmg8s672SbYCnVxVaBxH4lkbKM4sd8lN3T62kWXoarbzRwoZIT6U5rhS4Msm769LTB8R6/MvdSo8ICrPNum0jT9TseYim1FJwnW5zZ6Zs3WWxeuOX5MTVFpWBfX6+QIbg+q6oIKyUd7opYPtD6OADjtnjmQfQ5L6ngNVrtyL5Lwtn+tlnaYDSFDzpjPEL+fB8ZZQIn7rVozdc6DFEtjqQwVloZf+NZohFCb1QIQX3PjhmKz5rgUfktekuCoF5rAlRoNkMF+epzgMxR4zHkYMnszc4WA8YuiYYVvgJtL57FuXc56skhsQZSxP1+7L098SYj7Lb4zhpFJgyrvHUrAmWGkfWacg=="
  customUserSealedPassword: "AgDDQPXe+AWg/Std1bjINdKki1s3U0xP7oyApXZNXJIErg9+HCUCcNCLTbnSbCMgl3D6Jl0ov7uWy5UQBMrK7RXSscJ9EdPpy2YZ/d5iPqtRgOdFyXvbCnImHK67dP8b6dAT5LYZS3aJcuMZSaIbxnardiy28KWHfnElzBWPy49VkhrHIN7CYzg8s+Xhwh7nTFBZxYrx2zwvvucxv/NnLECjYw8rP931GxrILSvQkC4a4W2MJ0ZkhHjCLKcQfo6boI2JlOR5Yj7pg08pXj6zmNd7wyuYomSVYZCkg7OVZRJbW8xoWNkRHYwudKLeKXDRYDhp6ExjatjW5wjMCDTUcfaPWbsWhtlsTNc83M2yeqDiPzEfK9EepQU5SDAXM5O3qw3CZ80p4Cexybf56ivirrrqAwVncygtdSLv2KvnHDjxEesWNp5zJn0nAAXvzM8T3875Ju12PDqPRwFsk2EdCAZMNFtgaJdF0gR1LtDno/BuSjz2VldvaoSzHtOEl0IB7KE/nDlgMMztNhn/YYH9Vas+x/iCxqedGOEGOIufR3mHPhGwt6ajGtJ9vxghK+i23fkfjfn2OiufzfM1C6//V8kGvq40w5oadi6VDyS8Cs9mzog4YKS3padTS0gRA7Brq8Swvidria88dwlGpQUQZ1PAC+Ugid+gz9zBvJOtaJtnOQhGtO2/cjeZTQkEWIzBM+SSd+7AufoHYadP/g=="
  postgresSealedPassword: "AgBWpAROUqSDF5QiNocXb8Oft6eTP9/HWuLXgTzfFg0YxvORLQh9/BRpLt8mIfHjnyI+ay7luwI449Kw2bj7Q3wZFebeyV628xHYcdA3hSIWa3rCsJNTzPHTNUg+vPJbcTR9zi2FQcIvfRP+/TutCMwHUqAnoYE1/tYFgt9lH9Az+klkoL0Udsqtdfo+9M92n0FyTRAY+/lhDok2CACkbT3OyMttR7eJcpPcUM1QWD58wgm5ncKUXMSccXHtzN7DXPGSTabTbdmgW5w0u9KaSZA7UnE6yF9Kx5DeIynqsj1L5urma4XChwiF6noJtgAdqCr+Rd9ToFb+HSZCWlBQ2K7psfwK5GmDfatJs7XWZofqnzWxAnPckTkUm3dyIQnd9HgCVKBftaVrfOISm22bzL5yFBGRqUrVCVdVqghGO6r+DAaRV+FghL2Tb9Umh79yUSPmyU66akU/jo7QDP72L3r90LcVS2vijZYORXAxV5jiaTc9k40DuuoKTRnSeGeghwSQUqqbhTCFPsEuLpEhWITV5T0r+I+8JqC96MK84XHvNeTEZHot0b/ohPcP1eUTx6RqgOx0B04X9uDLtQ3CubFlbqfqPPw+mzW547fcGfuWT7WAtkg026eBf0m1PEV0D6hNs2BSB7NzdszrGtm36Qxgbc5N9Jh90RXK6NqEDcasSfBar+GqsLHNtVPeyCKr5xdNP3BozqCVHzzqmQ=="


