## @param namespace place where the chart will be stored
#
namespace: "company-2-ns"

## @param generalStorageClass responsible for creating persistance volume which will be used in keycloak mounting
# this value in system in persistanceVolume
generalStorageClass:
  storageName: "keycloak-company-2-storage-class"
  provisioner: kubernetes.io/no-provisioner

## @param generalPersistentVolume used for storing keycloak data
##
generalPersistentVolume:
  ## @param generalPersistentVolume.name must be unic for the whole cluster
  ##
  name: "keycloak-general-pv-company-2"
  ## @param generalPersistentVolume.capacity - must be the same that in keycloak, could be increased 
  ##
  capacity: 8Gi
  hostPath: "/mnt/data/keycloak/company-2"

## @param efsStorage must be linked to existing storageClass
#
efsStorage:
  storageName: "efs-sc"
  provisioner: efs.csi.aws.com

## @param efsPersistentVolume - used for provisioning efs storage
##
efsPersistentVolume:
  ## @param efsPersistentVolume.name must be unic for the whole cluster
  ##
  name: "keycloak-efs-pv-company-2"
  capacity: 1Gi
  ## @param efsPersistentVolume.volumeHandle - EFS the same for each keycloak customer, 
  ## way unic for each customer to avoid sharing the same files, 
  ## ATTENTION folder must be created before provisioning
  ##
  volumeHandle: "fs-0db109d8bea20374f:/keycloak/user-3-themes"

## @param efsPersistentVolumeClaim 
##
efsPersistentVolumeClaim:
  name: "keycloak-pv-claim"
  requestStorage: 1Gi

tlsCertificate:
  name: "keycloak-staging"
  server: "https://acme-staging-v02.api.letsencrypt.org/directory" #"https://acme-v02.api.letsencrypt.org/directory"
  email: "bbohatovmif@gmail.com"
  ingressClass: nginx
  privateKeyName: prod-secret-key

sealedSecret:
  postgresSecretName: "keycloak-postgresql-company-2-secret"
  keycloakSecretName: "keycloak-app-company-2-secret"
  instanceLabel: "keycloak-company-2-application"
  adminSealedPassword: "AgC9LXHh2XJ5vJks3WHlcar4StDAF9qFHuKGdLaWrZtc+oe8EkCaQKvykGwUZAgRTl95l9IDaQybeNacvtPgGF4U069pZ2+Fvs2UYyKyiv/PxPJ3kQx2AxYPlOFIOPE8NZuloUV5TspaML/bFSqXoaI61nRnJv9zyjmwQcJzlOvyakU+itFUPuLqaD/BOFMdtSYjlThL/hNxkCJthKRIuSKLUGkiAy+ht6t4DTAVPI4Upq6I2K6KmVTz1d6BDhICeeyECrz4M3mf47ovxLDPGY7kaDWYnhzjS2480ukDAMrIA5S+a+SoxtW/v456lPyqFH2ccwguIIkYaWhSzpORLjFU58m4K6Dg5LVl6IHez1C3Z7HpCZeJBLJI1jUQUPTz5oMTUa7zGHKtDR9lh3AanJ8JgQiipcgkYoEJyBPu641kSKTh7Bgtn0YisCTLUY5wsK4oCkyBH6CLJq/l96aWAJYqAhN/80V3mrF5VhjHVYt7W1gZoFfTqpQnWadxkCXtKfgLmzQpiXdmkYPxYrIpU/EFJFOWlRG4l3FtE5L76M9jwleQPma0jxvpJT2D50tTT7VR6EFjFmjFSZHeTZHBoH8cCCxAu6G1I74LALK3FxuleYajVSPW4OcXloaJBclmgrd8dZbhqX4mkDCWJimqSLorw2ltTs+83n8ZZYtqTxI4SyCA4NTjoe1Hi8abeldSJoyScx4vk5XY1iYU"
  customUserSealedPassword: "AgBVoCRy2JcwnaEGZMKhzJqnvBdrI0pD5hbmaYOMH5XlNXwCfISIIucL23fJPig6RZq+MC++QY7sQ9IXtAoPqFuW+1ujWpXKrk2Af4GZwcdyoLPZMHRaJLfFBumASlbeKlnftOvIjmPstV09Um7bz6ak2p64rczX+/LOmp8xTnyNWBcmlo2iUmUUax+Ip589HLDNxbct+HC8sFZz7kB1xg4mCu+avT5oAmS8+DnxR30LHNLy0eRqOLG05bGnf8Owc9CKZJRRYRwnfw1vIPRAB/Crgqg2ZqXPKAxczYgVpgxA3+dubNHXVvtxmojUP2cKHSBjrKq0UPILq6XF4l9JvEaojkLNaJUGGXRuEYEMpnsEZcHIfa+AMIfQc1lK9xMS1agpAX7YlgmMqrg02EjYIAubrYDfVEkOyJM/+tzcN9yMDdQqx9BpjAy0v040Cfo1zw3XX0/CjkX0j0FJdoTb/yCB3c2P4IEEZoG1rsVqbvZmL/bUrMGXRh/wfdf+JJEd+bx+kIraSFEAOya53831PLrOhvhff0emz+fcL6cW/1fWdgSspzPJBcGhHPqIIpScXeStvo8WLctaqbY6rU9OAN99B2EISNfbA7/GywEJN80bESI98g4D1SIVA3Se42vHkvSfXD/W6508wEh94rdmIsophaIfDNyy5AF+ETZEzhaQS9YXWrcfOtBt7GewShgQkfAWd+mBtqUEiM6s"
  postgresSealedPassword: "AgCvNcaw/1ITqRGc1Oym1e8k6Zae1WZEjqofHn3Xy2ProyRf5eiRmgOTyy1lA2Q68Z90UUVRRej+Ix2hAxPRrIGzBhQNDsGEtLU/a17S/iyVtIHiVwgJz+XX6A7eDe1R5mDtSzL+Xo8pdFd6hMoFQTcLBXEJhR4ZKaMB/+pGbo6AwdgW3BwAsXztVNwnbi6NL8ai0cXUG9blcnsrzvmgtXtoV5BJVx31bt9Z1Do1of9PspHfQGfplUUxfq9Ie4YBaCPvXx/SP4LMgExnoWQoczv3ZNa3n9BYKdv2/q+CfpbzCW2owntgWTt6MSGM7zPzc+tP/XbuVtkUJCat02wv2lvLKSRn0h9koy+AugIRfK8KZPVZclNgr6FNrIo/10tv8nTlVS7/MYhlCENLqr5ahUqr0vsAZiYFpB99zwZ/6apEPcKSwXAmpWgpvtxpIzMGE8JIA9zk0DkKM+Bk1L57pHxnX4vhLExKHvSji1pmLBgfw5qJ8fp1bm32yzds9ogAmbIdu3ZqkCczu7HYXrEhkWUzfI5/Mz4/51slex/gatqSZTZi6j0MpIIHoKMzNQxLyeMNmISAq3330wUNGjyRNBT57gkj2twiB7ljcq+KIcRcGjFKVuB4BnliudALRfdLz6W/nv3vj8nVE1dEOzznOP0HXJmoEul+KK9QpZOE7Ivcli5eTXTi/YVcdBHrcC8u3IBDP2ApU+s6AgQL"


