apiVersion: v1
kind: Namespace
metadata:
  name:  test-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: test-ns
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> out.txt; sleep 5; done"]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi